server:
  port: 9009
#服务名称
spring:
  application:
    name: qa-center
  datasource:
    url: jdbc:mysql://192.168.248.129:3306/tensquare_user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  mapper-locations: classpath:/entity/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.centralqa.entity


#eureka client
eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:1111/eureka  #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
    registry-fetch-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${randomServerPort.value[7000,7005]}}  #随机端口
    #instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/document.html #固定端口
#    status-page-url: http://${spring.cloud.client.ip-address}:${randomServerPort.value[7000,7005]}/document.html #随机端口

feign:
  hystrix:
    enabled: true
#隔离，不然当调用其他微服务是，feign调用报错，
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE


#日志输出等级
logging:
   level:
      com:
        capacity:
          qa: debug
