server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://192.168.248.129:3306/tensquare_base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver

  mapper-locations: classpath:/entity/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.article.entity
  redis:
    host: 192.168.248.129
logging:
   level:
      com:
        capacity:
          article: debug
