#server:
#  port: 9001
#spring:
#  application:
#      name: base-center
#  datasource:
#    url: jdbc:mysql://192.168.248.129:3306/tensquare_base?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root@123
#    driver-class-name: com.mysql.jdbc.Driver
#
#  mapper-locations: classpath:/entity/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.capacity.base.entity
#  rabbitmq:
#    host: 192.168.248.129
#    port: 5672
#    password: root
#    username: root
#logging:
#   level:
#      com:
#        capacity:
#          base: debug
#
#
##eureka client
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:  http://127.0.0.1:1111/eureka  #http://130.75.131.241:8761/eureka,http://130.75.131.248:8762/eureka
#      #http://134.224.249.33:1111/eureka/  正式库
#      #http://134.224.249.33:1111/eureka/  测试库
#      #http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
#    registry-fetch-interval-seconds: 10
#    instance-info-replication-interval-seconds: 10
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}  #固定端口
##    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${randomServerPort.value[7000,7005]}}  #随机端口
#    #instance-id: ${spring.application.name}:${docker.ipAddress}:${spring.application.instance_id:${server.port}}
#    lease-renewal-interval-in-seconds: 5  #每隔几秒告诉eureka服务器我还存活，用于心跳检测
#    lease-expiration-duration-in-seconds: 10 #如果心跳检测一直没有发送，10秒后会从eureka服务器中将此服务剔除
#    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/document.html #固定端口
